# Generated by Django 5.1.3 on 2024-11-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('state', models.CharField(choices=[('Bihar', 'Bihar'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Gujrat', 'Gujrat')], max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('pImage', models.ImageField(blank=True, upload_to='pImages')),
                ('rdoc', models.FileField(blank=True, upload_to='rdocs')),
            ],
        ),
    ]
